language: node_js
node_js:
- '6'
install:
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- sudo apt-get install jq
- cd ./bin && npm install && cd ../
script:
- "./bin/deploy-categories.sh"
- "./bin/deploy-articles.sh"
addons:
  ssh_known_hosts:
  - 104.197.69.102
branches:
  only:
  - master
notifications:
  email: false
  slack:
    rooms:
      secure: mhPqkWM3n5vFIY98UOFjPH5cEo1ps1Ced+4BzyfIIvR1l4x6kzPnM7U49fEjTlsyRt0LIufXralBhaTcTx3uT/RMdi1NcVSfMzWTsrgULduUb0y5Us+alchdhtBasidz2QYIqNewJrRwMPGUXO1Hs3N/j/X7jmpAiy9uqUVRaLcilyUomMQXKMAm+bII7duZCkUvq1RZxv88jRbHnllfOL7Od2ffo4r8vkTkKQXF71jKvhTB73yk0czto4U6UhscjP/cYXPe+r2IFNyA+b6Ow0plKRRC0VrtY7o6dP1f/TRZkHr1AFJY0NQJ1EpxtpkKdBdz67YgNXqoE5CmVxLook1vFZEuYcfF7GtDf523Hh7VTzYhd11sIqUohQwXyqc/HJxSSqhKdnJhZF/zlbUzE+uuaPneR4wgY5AK11pVft0z5r7CkVLEf5Y1A61wepYkaa4WkDn7WVW1hAn7rmj1cXTiEr5lo8o3Tc5CkV3iSagNJGXtN/S/ohOY+OpxjIzhU+BbA5cvbiS4NEpK3L2ELm1i41HL86Zzd1ORYBEqSPnJqqu+0SSrLXIuMC0/7Hj1hWT8ZTzyReeCbwUkEQe20zAplcQTlS/bdSGNwoO8tDUcECKKINoXBH9JmsyaY4NZp5rsuBhaBiHi0pl7qG0Aa5l8EA+orDUunHAUf5wxevA=
before_install:
- openssl aes-256-cbc -K $encrypted_e85ef5fe888e_key -iv $encrypted_e85ef5fe888e_iv
  -in deploy-key.enc -out deploy-key -d
- "./bin/setup.sh"
