backend:
  name: github
  repo: SparkPost/support-docs
  branch: cms
publish_mode: editorial_workflow
media_folder: global_media
collections: 
  - label: Billing
    name: billing
    label_singular: Integration
    folder: "/articles/billing"
    create: true
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Notification, name: notification, widget: string }
      - { label: Body, name: body, widget: markdown }